Add Ruff
cachix/pre-commit-hooks.nix pull request #227
Opened 2023-01-12 23:23 UTC by shikanime

Ruff is a Python linter that is starting to get a lot of attention lately.

2023-01-13 12:39 UTC, loicreynier requested changes

2023-01-13 12:39 UTC, loicreynier commented on modules/hooks.nix
> +          types = [ "file" "python" ];
```suggestion
          types = [ "python" ];
```

The type `file` is not necessary when using the `python` type.

2023-01-13 12:39 UTC, loicreynier commented on modules/hooks.nix
> +          entry = "${pkgs.python3Packages.black}/bin/ruff";
```suggestion
          entry = "${pkgs.ruff}/bin/ruff";
```

`ruff` is not a Python package.

2023-01-13 12:45 UTC, loicreynier requested changes

2023-01-13 12:45 UTC, loicreynier commented on nix/tools.nix
> +  inherit actionlint alejandra cabal-fmt cabal2nix cargo clang-tools clippy deadnix dhall editorconfig-checker hadolint hindent hlint hpack html-tidy nix-linter nixfmt nixpkgs-fmt ormolu rustfmt shel
`ruff` should also be added to the arguments line 32.

2023-01-13 17:40 UTC, shikanime commented
Oh, at the moment, it seems that Ruff is only available on Nixpkgs version 22.11.

2023-01-18 16:04 UTC, domenkozar commented
I'll try to bump checks to 22.11

2023-01-18 20:55 UTC, domenkozar commented
If you rebase it should work now

2023-01-19 09:56 UTC, merged

2023-01-22 20:17 UTC, dhess commented
FYI, I believe this commit broke the flake. We now get:

```
error: Function called without required argument "ruff" at /nix/store/lvwknwz9wfx66qyxdcak5p6w2wfxlzpd-source/nix/tools.nix:32, did you mean "duff", "guff" or "rufo"?
```

2023-01-23 00:40 UTC, shikanime commented
Please correct me if I'm wrong, as the package is only available in 22.11 release, should I have added a default to null ?

2023-01-23 00:58 UTC, dhess commented
@shikanime Possibly. This happens when I use `pre-commit-hooks.nix` with `haskell.nix`, which is, I believe, using a pre-22.11 nixpkgs-unstable pin. There's a PR to bump it: https://github.com/input-output-hk/haskell.nix/pull/1815

2023-01-23 01:24 UTC, shikanime commented
Thanks for the extra details, I didn't realize the follows mechanism worked like that after reading the documentation.
I haven't had much experience with Flake dependencies system.
Sorry for the inconveniences (⁠｡⁠ŏ⁠﹏⁠ŏ⁠)

2023-01-23 09:30 UTC, dhess commented
No worries at all, thanks for the contribution.