Add config option to add custom user defined hooks
cachix/pre-commit-hooks.nix pull request #92
Opened 2020-12-30 23:45 UTC by u-quark

Sometimes it is useful to add a project specific command as an extra
check that is not part of the pre-defined set of hooks provided by this
project.

Closes #86.

2020-12-31 13:10 UTC, roberth requested changes
Hi @u-quark, thank you for helping out with custom hooks. They were already supported but not documented though (see suggestion comment). If we change things around a bit we can make it even better.

The reason I think we should avoid the new syntax is because it is inconsistent, creating a difference between custom and built-in hooks, which is not needed. It's similar to NixOS's `users.extraUsers` tech debt. The hidden strength of the module system is that "built-in" modules aren't any different from configuration modules.

We could change the default value of `enable` to `true` and explicitly disable them in the built-in hooks. I don't expect that to break much, because it seems safe to assume that without documentation for it, nobody creates their own 'libraries' of hooks.

2020-12-31 14:45 UTC, u-quark commented
This is so much better! I tried doing this before but run into a misleading error and assumed it is not possible. Thanks for the help. I updated this PR to only include documentation for how to do this based on your suggestion.

I don't think the `enable` flag is a big deal at the moment.

2021-01-04 17:24 UTC, merged

2021-01-04 17:30 UTC, u-quark commented
Thanks!

2021-01-04 17:30 UTC, chiroptical commented
Very cool! Thanks @u-quark

2021-04-17 17:32 UTC, quasi-coherent commented
How is this meant to work?  I absolutely have a Makefile target called `gen`, but when I run this hook
```nix
gen = {
  enable = true;
  name = "Generate code from spec";
  entry = "make gen";
};
```
I get
```
Generate code from spec..........................................Failed
- hook id: gen
- exit code: 2

make: *** No rule to make target 'gen'.  Stop.
make: *** No rule to make target 'gen'.  Stop.
make: *** No rule to make target 'gen'.  Stop.
make: *** No rule to make target 'gen'.  Stop.
make: *** No rule to make target 'gen'.  Stop.
make: *** No rule to make target 'gen'.  Stop.
```

2021-04-19 08:34 UTC, domenkozar commented
You can specify directory with `make -C dir`